Add initial undo command

diff --git a/mq b/mq
--- a/mq
+++ b/mq
@@ -27,11 +27,12 @@
 #
 #   - Add individual command help functions
 #   - Add individual command bash complete function (if possible - probably not worth the effort)
+#   - Add better param parsing.
 #
 ##
 ######################
 
-VERSION=1.0.11
+VERSION=1.0.12
 
 
 # bash complete functions
@@ -271,6 +272,9 @@ function check_uncommitted_changes {
             echo "There are uncommitted changes in your working branch. You need to commit these before running this command."
             exit 1;
         fi
+        if [[ "${1}" == "silent" ]]; then
+            return 1;
+        fi
         echo "There are uncommitted changes in your working branch:"
         hg status
         echo
@@ -279,6 +283,9 @@ function check_uncommitted_changes {
             echo "abort: commit changes before retrying your command."
             exit 0;
         fi
+    fi
+    if [[ "${1}" == "silent" ]]; then
+        return 0;
     fi
 }
 
@@ -868,6 +875,49 @@ ${HG_STATUS}
     echo
 }
 
+mq_undo() { #-- Pull the last commit back into your patch queue. This will undo a mq finish so long as it is still mutable
+    check_hg_repo;
+    # TODO: If a patch already exists, check if we want to squash it
+    if [[ -s $(project_patch_dir)/series ]]; then 
+        echo "abort: and active patch already exists"; 
+        exit 1
+    fi
+    if [[ -s $(project_patch_dir)/status ]]; then 
+        echo "abort: and active patch already exists"; 
+        exit 1
+    fi
+    if [[ ! ${2} ]]; then
+        echo "abort: no name specified";
+        echo
+        echo "Usage: mq undo [NAME]";
+        echo
+        exit 1
+    fi
+    project=$(working_project);
+    name=$(printf "${PATCH_NAMING}" "${2}")_${project};
+    mutable_changes=$(hg log -r "reverse(secret())" -r "reverse(draft())" --template "{node}\n" -l 1);
+    selection="";
+    for commit in ${mutable_changes}; do
+        echo
+        hg log -r ${commit};
+        read -p "Convert this commit to a patch? (y/n) " AN;
+        case "${AN}" in
+            [yY] | [yY][Ee][Ss] )
+                echo "Selecting commit ${commit}"
+                selection="${selection} ${commit}";
+                ;;
+            [nN] | [n|N][O|o] )
+                echo "Ignoring commit ${commit}"
+                ;;
+            *) echo "That was not a valit selection."
+               ;;
+        esac
+    done
+    if [[ ! -z ${selection} ]]; then
+        hg qimport --name ${name} --git --rev ${selection};
+    fi
+}
+
 mq_wiggle() { #-- Find and attempt to resolve failed hunks of an applied patch using wiggle.
     check_hg_repo;
     find . -type f -name "*.rej" -print0 | while IFS= read -r -d '' rej_file; do
@@ -886,7 +936,6 @@ mq_version() { #-- Output version and copyright information.
         line=$(echo "$line" | sed -r 's/[#]+/ /g');
         echo "    $line";
     done <<< $(head -n 21 "${BASH_SOURCE[0]}");
-
 }
 
 ### Env setup ----------------------------------------------------
