mq new should require a argument for the name of the patch

diff --git a/mq b/mq
--- a/mq
+++ b/mq
@@ -369,6 +369,13 @@ mq_new() { #-- Generate new patch for current working branch.
         echo "abort: and active patch already exists"; 
         exit 1
     fi
+    if [[ ! ${2} ]]; then
+        echo "abort: no name specified";
+        echo
+        echo "Usage: mq new [NAME]";
+        echo
+        exit 1
+    fi
     project=$(working_project)
     name=$(printf "${PATCH_NAMING}" "${2}")_${project};
     hg qnew ${name} ${@:3} --git --currentuser;
