add "hg rename" function

diff --git a/mq b/mq
--- a/mq
+++ b/mq
@@ -32,7 +32,7 @@
 ##
 ######################
 
-VERSION=1.0.14
+VERSION=1.0.15
 
 
 # bash complete functions
@@ -841,6 +841,29 @@ mq_rebase() { #-- Rebase your patch to sit above the current branch tip.
     # First check if there are uncommitted changes and warn user
     check_uncommitted_changes
     rebase_patch --rebase
+}
+
+mq_rename() { #-- Rename your applied patch file
+    check_hg_repo
+    project=$(working_project)
+    applied_patch=$(hg qseries);
+    applied_patch=${applied_patch[0]};
+    if [[ ! ${2} ]]; then
+        echo "abort: you need to provide a new name";
+        echo
+        echo "Usage: mq rename [NAME]";
+        echo
+        exit 1
+    fi
+    new_name=$(printf "${PATCH_NAMING}" "${2}")_${project};
+    if [[ ${new_name} == ${applied_patch} ]]; then
+        echo "abort: your patch is already named ${2}";
+        echo
+        echo "Usage: mq rename [NAME]";
+        echo
+        exit 1
+    fi
+    hg qrename ${applied_patch} ${new_name};
 }
 
 mq_squash() { #-- Squash one or more revisions from the working branch into a single patch file.
